import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import {
  ConversationMessage,
  needsWebSearch,
  performTavilySearch,
  scrapeUrl,
  buildSystemPrompt,
  extractUrls,
  parseCommand,
  formatForWhatsApp,
  getHelpMessage,
  formatPoll,
  isTimeQuery,
  getTimeForLocation,
  extractSocialMediaQuery,
  selectModel,
  analyzeImage,
  transcribeAudio,
  generateVoiceResponse,
  detectImageGenerationRequest,
  generateImage,
  searchKnowledgeBase,
  saveToKnowledgeBase,
  detectCorrection,
  extractQueryPattern,
  learnFromWebSearch,
  detectMemoryCommand,
  saveUserMemory,
  getUserMemories,
  deleteUserMemories,
  formatMemoriesForPrompt,
  saveDocumentToHistory,
  searchDocumentHistory,
  getDocumentHistoryList,
  detectDocumentReference,
  formatDocumentHistoryForPrompt,
  generateDocumentSummary,
} from "../_shared/phoenix-core.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const ULTRAMSG_BASE = 'https://api.ultramsg.com';

// UltraMsg webhook payload
interface UltraMsgWebhook {
  event_type: string;
  instanceId: string;
  data: {
    id: string;
    from: string;
    to: string;
    ack: string;
    type: string;
    body: string;
    media?: string;
    caption?: string;
    fromMe: boolean;
    isForwarded: boolean;
    time: number;
    pushname?: string;
    isGroup?: boolean;
    participant?: string;
    quotedMsg?: {
      type: string;
      body: string;
      caption?: string;
      fromMe?: boolean;
      participant?: string;
    };
  };
}

// Send text message via UltraMsg
async function sendMessage(to: string, body: string, instanceId: string, token: string): Promise<void> {
  try {
    const formatted = formatForWhatsApp(body);
    const maxLength = 4000;
    const chunks: string[] = [];

    if (formatted.length > maxLength) {
      let remaining = formatted;
      while (remaining.length > 0) {
        let splitIndex = maxLength;
        if (remaining.length > maxLength) {
          const lastNewline = remaining.lastIndexOf('\n', maxLength);
          const lastSpace = remaining.lastIndexOf(' ', maxLength);
          splitIndex = Math.max(lastNewline, lastSpace, maxLength / 2);
        }
        chunks.push(remaining.slice(0, splitIndex));
        remaining = remaining.slice(splitIndex).trim();
      }
    } else {
      chunks.push(formatted);
    }

    for (const chunk of chunks) {
      const response = await fetch(`${ULTRAMSG_BASE}/${instanceId}/messages/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token, to, body: chunk }),
      });

      if (!response.ok) {
        console.error('UltraMsg send failed:', await response.text());
      }

      if (chunks.length > 1) {
        await new Promise(r => setTimeout(r, 500));
      }
    }
  } catch (error) {
    console.error('Send message error:', error);
  }
}

// Send image via UltraMsg
async function sendImageMessage(
  to: string,
  imageBase64: string,
  caption: string,
  instanceId: string,
  token: string
): Promise<boolean> {
  try {
    const response = await fetch(`${ULTRAMSG_BASE}/${instanceId}/messages/image`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        token,
        to,
        image: `data:image/png;base64,${imageBase64}`,
        caption: caption || '🎨 Generated by Phoenix AI',
      }),
    });

    if (response.ok) {
      console.log('✅ Image sent via UltraMsg');
      return true;
    }
    console.error('UltraMsg image send failed:', await response.text());
    return false;
  } catch (error) {
    console.error('Image send error:', error);
    return false;
  }
}

// Send voice via UltraMsg
async function sendVoiceMessage(
  to: string,
  audioBuffer: ArrayBuffer,
  instanceId: string,
  token: string
): Promise<boolean> {
  try {
    // Convert ArrayBuffer to base64
    const uint8 = new Uint8Array(audioBuffer);
    let binaryStr = '';
    for (let i = 0; i < uint8.length; i++) {
      binaryStr += String.fromCharCode(uint8[i]);
    }
    const audioBase64 = btoa(binaryStr);

    const response = await fetch(`${ULTRAMSG_BASE}/${instanceId}/messages/voice`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        token,
        to,
        audio: `data:audio/mpeg;base64,${audioBase64}`,
      }),
    });

    if (response.ok) {
      console.log('✅ Voice sent via UltraMsg');
      return true;
    }
    console.error('UltraMsg voice send failed:', await response.text());
    return false;
  } catch (error) {
    console.error('Voice send error:', error);
    return false;
  }
}

// Get or create conversation (reuses whatsapp_conversations table)
async function getOrCreateConversation(supabase: any, chatId: string, senderName: string) {
  const { data: existing } = await supabase
    .from('whatsapp_conversations')
    .select('*')
    .eq('chat_id', chatId)
    .single();

  if (existing) {
    await supabase
      .from('whatsapp_conversations')
      .update({ updated_at: new Date().toISOString(), sender_name: senderName })
      .eq('id', existing.id);
    return existing;
  }

  const { data: newConv, error } = await supabase
    .from('whatsapp_conversations')
    .insert({ chat_id: chatId, sender_name: senderName })
    .select('*')
    .single();

  if (error) throw error;
  return newConv;
}

// Get conversation history
async function getConversationHistory(supabase: any, chatId: string, limit = 50): Promise<ConversationMessage[]> {
  const { data: messages, error } = await supabase
    .from('whatsapp_messages')
    .select('role, content, created_at')
    .eq('chat_id', chatId)
    .order('created_at', { ascending: false })
    .limit(limit);

  if (error || !messages || messages.length === 0) return [];

  return messages.reverse().map((m: any) => ({
    role: m.role as 'user' | 'assistant',
    content: m.content,
  }));
}

// Save message
async function saveMessage(supabase: any, conversationId: string, chatId: string, role: 'user' | 'assistant', content: string) {
  const { error } = await supabase.from('whatsapp_messages').insert({
    conversation_id: conversationId,
    chat_id: chatId,
    role,
    content,
  });
  if (error) console.error('Save message error:', error);
}

// Clear conversation
async function clearConversation(supabase: any, chatId: string) {
  await supabase.from('whatsapp_messages').delete().eq('chat_id', chatId);
}

// ===== Multi-document buffering =====

async function storePendingDocument(
  supabase: any, chatId: string, fileName: string, extractedText: string
): Promise<number> {
  await supabase.from('pending_documents').delete()
    .eq('chat_id', chatId)
    .lt('created_at', new Date(Date.now() - 5 * 60 * 1000).toISOString());

  await supabase.from('pending_documents').insert({
    chat_id: chatId, platform: 'ultramsg', file_name: fileName, extracted_text: extractedText,
  });

  const { count } = await supabase.from('pending_documents')
    .select('*', { count: 'exact', head: true })
    .eq('chat_id', chatId);
  return count || 1;
}

async function getPendingDocuments(supabase: any, chatId: string): Promise<{ file_name: string; extracted_text: string }[]> {
  const { data } = await supabase.from('pending_documents')
    .select('file_name, extracted_text')
    .eq('chat_id', chatId)
    .order('created_at', { ascending: true });
  return data || [];
}

async function clearPendingDocuments(supabase: any, chatId: string): Promise<void> {
  await supabase.from('pending_documents').delete().eq('chat_id', chatId);
}

async function compareDocuments(
  docs: { file_name: string; extracted_text: string }[],
  userPrompt: string,
  senderName: string,
  conversationHistory: ConversationMessage[],
  preferredLanguage: string | undefined,
  supabase: any,
  chatId: string
): Promise<string> {
  const maxCharsPerDoc = Math.floor(25000 / docs.length);
  let docSections = '';
  for (let i = 0; i < docs.length; i++) {
    let text = docs[i].extracted_text;
    if (text.length > maxCharsPerDoc) text = text.slice(0, maxCharsPerDoc) + '\n[... truncated ...]';
    docSections += `\n\n=== DOCUMENT ${i + 1}: "${docs[i].file_name}" ===\n${text}\n=== END DOCUMENT ${i + 1} ===\n`;
  }

  return processWithPhoenixAI(
    userPrompt || `Compare these ${docs.length} documents. Highlight key similarities, differences, and unique content in each.`,
    senderName, conversationHistory, preferredLanguage,
    `\n\n📄 MULTI-DOCUMENT COMPARISON (${docs.length} documents):${docSections}`,
    supabase, chatId
  );
}

// Update conversation language
async function updateConversationLanguage(supabase: any, conversationId: string, language: string) {
  await supabase
    .from('whatsapp_conversations')
    .update({ preferred_language: language })
    .eq('id', conversationId);
}

// Check if message is from a group
function isGroupChat(chatId: string): boolean {
  return chatId.includes('@g.us');
}

// Check if bot should respond in group
function shouldRespondInGroup(webhook: UltraMsgWebhook): boolean {
  const body = (webhook.data?.body || '').toLowerCase();
  const quotedMsg = webhook.data?.quotedMsg;

  // Check for name mentions
  const isMentioned = body.includes('@phoenix') ||
    body.includes('phoenix ai') ||
    body.includes('hey phoenix') ||
    body.includes('phoenix');

  // Check if replied (swiped) to a bot message
  const isReplyToBot = quotedMsg && (
    quotedMsg.fromMe === true ||
    (quotedMsg.body || '').endsWith('🔥') ||
    (quotedMsg.body || '').toLowerCase().includes('phoenix')
  );

  if (isMentioned || isReplyToBot) {
    console.log('👥 Group: responding -', isMentioned ? 'mentioned' : 'reply-to-bot');
    return true;
  }

  return false;
}

// Process with Phoenix AI
async function processWithPhoenixAI(
  message: string,
  senderName: string,
  conversationHistory: ConversationMessage[],
  preferredLanguage?: string,
  messageContext?: string,
  supabase?: any,
  platformUserId?: string
): Promise<string> {
  const lovableApiKey = Deno.env.get('LOVABLE_API_KEY')!;
  const tavilyApiKey = Deno.env.get('TAVILY_API_KEY');
  const firecrawlApiKey = Deno.env.get('FIRECRAWL_API_KEY');

  let memoriesContext = '';
  if (supabase && platformUserId) {
    const memories = await getUserMemories(supabase, 'whatsapp', platformUserId);
    memoriesContext = formatMemoriesForPrompt(memories);
    
    // Add document history list to system prompt
    const docHistory = await getDocumentHistoryList(supabase, 'whatsapp', platformUserId);
    memoriesContext += formatDocumentHistoryForPrompt(docHistory);
  }
  
  // Check for document reference in message  
  const docRef = detectDocumentReference(message);
  if (docRef.hasReference && docRef.fileName && supabase && platformUserId) {
    const matchedDocs = await searchDocumentHistory(supabase, 'whatsapp', platformUserId, docRef.fileName);
    if (matchedDocs.length > 0) {
      const doc = matchedDocs[0];
      const docContent = doc.extracted_text.slice(0, 15000);
      messageContext = (messageContext || '') + `\n\n📄 REFERENCED DOCUMENT "${doc.file_name}":\n---\n${docContent}\n---`;
      console.log('📄 Injected document context:', doc.file_name);
    }
  }

  const systemPrompt = buildSystemPrompt({
    senderName,
    isWhatsApp: true,
    savedLanguage: preferredLanguage,
  }) + memoriesContext;

  let webContext = messageContext || '';

  // Check knowledge base
  if (supabase) {
    const knowledgeEntry = await searchKnowledgeBase(supabase, message);
    if (knowledgeEntry) {
      webContext += `\n\n[KNOWLEDGE-REF] ${knowledgeEntry.verified_answer}`;
      if (knowledgeEntry.source_url) webContext += ` (ref: ${knowledgeEntry.source_url})`;
    }

    const correctionCheck = detectCorrection(message);
    if (correctionCheck.isCorrection && correctionCheck.correctedInfo) {
      const queryPattern = extractQueryPattern(correctionCheck.correctedInfo, conversationHistory);
      await saveToKnowledgeBase(supabase, queryPattern, correctionCheck.correctedInfo, undefined, 'user_correction');
      webContext += `\n\n[LEARNING-ACK] Correction saved internally.`;
    }
  }

  // Time queries
  const timeCheck = isTimeQuery(message);
  if (timeCheck.isTime && timeCheck.location) {
    const timeInfo = getTimeForLocation(timeCheck.location);
    if (timeInfo) webContext += `\n\n⏰ TIME INFO: ${timeInfo}`;
  }

  // URLs
  const urls = extractUrls(message);
  if (urls.length > 0 && firecrawlApiKey) {
    for (const url of urls.slice(0, 2)) {
      const content = await scrapeUrl(url, firecrawlApiKey);
      if (content) {
        const truncated = content.length > 5000 ? content.slice(0, 5000) + '...' : content;
        webContext += `\n\n📄 Content from ${url}:\n${truncated}`;
      }
    }
  }

  // Social media
  const socialQuery = extractSocialMediaQuery(message);
  if (socialQuery && tavilyApiKey) {
    const results = await performTavilySearch(socialQuery.query, tavilyApiKey);
    if (results.results.length > 0) {
      webContext += `\n\n🔍 ${socialQuery.platform} Search Results:\n`;
      if (results.answer) webContext += `Summary: ${results.answer}\n\n`;
      for (const r of results.results.slice(0, 5)) {
        webContext += `• ${r.title}: ${r.content.slice(0, 400)}\nSource: ${r.url}\n\n`;
      }
      if (supabase) await learnFromWebSearch(supabase, socialQuery.query, results, 'social_media');
    }
  }

  // General web search
  const searchCheck = needsWebSearch(message);
  if (searchCheck.needed && !socialQuery && tavilyApiKey && webContext.length < 500) {
    const results = await performTavilySearch(searchCheck.query, tavilyApiKey);
    if (results.results.length > 0) {
      webContext += '\n\n🔍 Live Web Search Results:\n';
      if (results.answer) webContext += `Quick Answer: ${results.answer}\n\n`;
      for (const r of results.results.slice(0, 6)) {
        webContext += `• ${r.title}: ${r.content.slice(0, 500)}\nSource: ${r.url}\n\n`;
      }
      if (supabase) await learnFromWebSearch(supabase, searchCheck.query, results, 'web_search');
    }
  }

  const userContent = message + webContext;
  const model = selectModel(message, false, false);

  const messagesForAI = [
    { role: 'system', content: systemPrompt },
    ...conversationHistory.map(m => ({ role: m.role, content: m.content })),
    { role: 'user', content: userContent },
  ];

  const isOpenAIModel = model.startsWith('openai/');
  const tokenParam = isOpenAIModel ? { max_completion_tokens: 3000 } : { max_tokens: 3000 };

  const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${lovableApiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model,
      messages: messagesForAI,
      stream: false,
      ...tokenParam,
    }),
  });

  if (!aiResponse.ok) {
    if (aiResponse.status === 429) return "⚠️ Too many requests. Please wait a moment and try again.";
    if (aiResponse.status === 402) return "⚠️ Phoenix AI credits depleted. Please contact the administrator.";
    throw new Error('AI Gateway error: ' + aiResponse.status);
  }

  const data = await aiResponse.json();
  let response = data.choices?.[0]?.message?.content || "I couldn't generate a response. Please try again.";
  return formatForWhatsApp(response);
}

// ==============================
// MAIN HANDLER
// ==============================

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  if (req.method === 'GET') {
    return new Response('Phoenix AI UltraMsg Webhook Active 🔥', {
      headers: { ...corsHeaders, 'Content-Type': 'text/plain' },
    });
  }

  try {
    const instanceId = Deno.env.get('ULTRAMSG_INSTANCE_ID')!;
    const token = Deno.env.get('ULTRAMSG_TOKEN')!;
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const lovableApiKey = Deno.env.get('LOVABLE_API_KEY')!;
    const elevenLabsKey = Deno.env.get('ELEVENLABS_API_KEY');

    if (!instanceId || !token) {
      return new Response(
        JSON.stringify({ error: 'UltraMsg not configured' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const supabase = createClient(supabaseUrl, supabaseServiceKey);
    const webhook: UltraMsgWebhook = await req.json();

    console.log('📱 UltraMsg Webhook:', webhook.event_type, webhook.data?.from, 'Type:', webhook.data?.type);

    // Only handle incoming messages
    if (webhook.event_type !== 'message_received' && webhook.event_type !== 'message') {
      return new Response(
        JSON.stringify({ status: 'ignored', reason: webhook.event_type }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Skip messages from self
    if (webhook.data?.fromMe) {
      return new Response(
        JSON.stringify({ status: 'ignored', reason: 'fromMe' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const chatId = webhook.data?.from;
    const senderName = webhook.data?.pushname || 'User';
    const messageType = webhook.data?.type;

    if (!chatId) {
      return new Response(
        JSON.stringify({ error: 'No chat ID' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // For group chats, only respond if mentioned or replied to
    const isGroup = webhook.data?.isGroup || isGroupChat(chatId);
    if (isGroup) {
      if (!shouldRespondInGroup(webhook)) {
        return new Response(
          JSON.stringify({ status: 'ignored', reason: 'Not mentioned in group' }),
          { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
    }

    // Get or create conversation
    const conversation = await getOrCreateConversation(supabase, chatId, senderName);
    const history = await getConversationHistory(supabase, chatId, 30);

    // Handle image messages
    if (messageType === 'image' && webhook.data?.media) {
      console.log('🖼️ Processing image via UltraMsg');
      const caption = webhook.data?.caption || webhook.data?.body;
      const imageAnalysis = await analyzeImage(webhook.data.media, caption, lovableApiKey);

      if (imageAnalysis) {
        await saveMessage(supabase, conversation.id, chatId, 'user', `[Sent an image${caption ? `: "${caption}"` : ''}]`);

        let finalResponse = imageAnalysis;
        if (caption && (caption.includes('?') || caption.length > 10)) {
          finalResponse = await processWithPhoenixAI(
            caption,
            senderName,
            history,
            conversation.preferred_language,
            `\n\n🖼️ IMAGE ANALYSIS:\n${imageAnalysis}`,
            supabase,
            chatId
          );
        } else {
          finalResponse = `🖼️ *Image Analysis:*\n\n${imageAnalysis}`;
        }

        await saveMessage(supabase, conversation.id, chatId, 'assistant', finalResponse);
        await sendMessage(chatId, finalResponse, instanceId, token);

        return new Response(
          JSON.stringify({ status: 'success', type: 'image' }),
          { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }

      await sendMessage(chatId, "🖼️ I received your image but had trouble analyzing it. Could you try sending it again? 🔥", instanceId, token);
      return new Response(
        JSON.stringify({ status: 'partial', type: 'image' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Handle voice/audio messages
    if ((messageType === 'audio' || messageType === 'ptt') && webhook.data?.media) {
      console.log('🎤 Processing voice via UltraMsg');

      let transcription: string | null = null;
      if (elevenLabsKey) {
        transcription = await transcribeAudio(webhook.data.media, elevenLabsKey);
      }

      if (transcription) {
        await saveMessage(supabase, conversation.id, chatId, 'user', `[Voice message]: ${transcription}`);

        const aiResponse = await processWithPhoenixAI(
          transcription,
          senderName,
          history,
          conversation.preferred_language,
          undefined,
          supabase,
          chatId
        );

        await saveMessage(supabase, conversation.id, chatId, 'assistant', aiResponse);

        // Try to send voice response back if ElevenLabs is available
        let voiceSent = false;
        if (elevenLabsKey && aiResponse.length < 1000) {
          const voiceBuffer = await generateVoiceResponse(aiResponse, elevenLabsKey);
          if (voiceBuffer) {
            voiceSent = await sendVoiceMessage(chatId, voiceBuffer, instanceId, token);
          }
        }

        if (!voiceSent) {
          await sendMessage(chatId, aiResponse, instanceId, token);
        } else {
          await sendMessage(
            chatId,
            `📝 _Transcription: "${transcription.slice(0, 100)}${transcription.length > 100 ? '...' : ''}"_\n\n${aiResponse}`,
            instanceId,
            token
          );
        }

        return new Response(
          JSON.stringify({ status: 'success', type: 'voice', voiceResponse: voiceSent }),
          { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }

      await sendMessage(chatId, "🎤 I received your voice message but had trouble transcribing it. Please try again or type your message. 🔥", instanceId, token);
      return new Response(
        JSON.stringify({ status: 'partial', type: 'voice' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Handle document messages (PDF, DOCX, TXT, etc.)
    if (messageType === 'document' && webhook.data?.media) {
      console.log('📄 Processing document via UltraMsg');
      const fileName = webhook.data?.body || webhook.data?.caption || 'document';

      try {
        const docResp = await fetch(webhook.data.media);
        if (!docResp.ok) throw new Error('Failed to download document');
        const docBuffer = await docResp.arrayBuffer();
        const docBytes = new Uint8Array(docBuffer);

        const isTextFile = /\.(txt|md|csv|json|xml|html|css|js|ts|py|java|log|sh|yaml|yml|toml|ini)$/i.test(fileName);
        let docContent: string;

        if (isTextFile) {
          docContent = new TextDecoder().decode(docBytes);
          if (docContent.length > 30000) docContent = docContent.slice(0, 30000) + '\n\n[... truncated ...]';
        } else {
          let binaryStr = '';
          for (let i = 0; i < docBytes.length; i++) {
            binaryStr += String.fromCharCode(docBytes[i]);
          }
          const base64Doc = btoa(binaryStr);
          const mimeType = fileName.endsWith('.pdf') ? 'application/pdf' :
            fileName.endsWith('.docx') ? 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' :
            fileName.endsWith('.xlsx') ? 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' :
            'application/octet-stream';

          const extractResp = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
            method: 'POST',
            headers: {
              'Authorization': `Bearer ${lovableApiKey}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              model: 'google/gemini-2.5-flash',
              messages: [{
                role: 'user',
                content: [
                  { type: 'text', text: 'Extract ALL text content from this document. Preserve structure, headings, lists, and formatting. Return the full extracted text.' },
                  { type: 'image_url', image_url: { url: `data:${mimeType};base64,${base64Doc}` } },
                ],
              }],
              max_tokens: 8192,
            }),
          });

          if (extractResp.ok) {
            const extractData = await extractResp.json();
            docContent = extractData.choices?.[0]?.message?.content || '';
          } else {
            docContent = '[Could not extract text from this document format]';
          }
        }

        // Store in pending documents buffer
        const pendingCount = await storePendingDocument(supabase, chatId, fileName, docContent);

        // Save to document history for future reference
        const summary = await generateDocumentSummary(docContent, fileName, lovableApiKey);
        await saveDocumentToHistory(supabase, {
          platform: 'whatsapp',
          platformUserId: chatId,
          fileName,
          extractedText: docContent,
          summary,
        });

        if (pendingCount === 1) {
          await sendMessage(
            chatId,
            `📄 Got *${fileName}*! 📥\n\nSend more documents within 2 minutes to *compare them*, or reply *"analyze"* to process this one now. 🔥`,
            instanceId,
            token
          );
          return new Response(
            JSON.stringify({ status: 'buffered', type: 'document', pendingCount }),
            { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
          );
        } else {
          // 2+ documents - auto-trigger comparison
          const allDocs = await getPendingDocuments(supabase, chatId);
          await clearPendingDocuments(supabase, chatId);

          const docNames = allDocs.map(d => d.file_name).join(', ');
          await sendMessage(chatId, `📄 Comparing *${allDocs.length} documents*: ${docNames}... 🔥`, instanceId, token);

          await saveMessage(supabase, conversation.id, chatId, 'user', `[Sent ${allDocs.length} documents for comparison: ${docNames}]`);

          const caption = (webhook.data?.caption || '').trim();
          const comparisonResponse = await compareDocuments(
            allDocs, caption, senderName, history, conversation.preferred_language, supabase, chatId
          );

          await saveMessage(supabase, conversation.id, chatId, 'assistant', comparisonResponse);
          await sendMessage(chatId, comparisonResponse, instanceId, token);

          return new Response(
            JSON.stringify({ status: 'success', type: 'document_comparison', docCount: allDocs.length }),
            { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
          );
        }
      } catch (error) {
        console.error('Document analysis error:', error);
        await sendMessage(chatId, `📄 Sorry ${senderName}, I had trouble analyzing "${fileName}". Please try sending it again or paste the text directly. 🔥`, instanceId, token);
        return new Response(
          JSON.stringify({ status: 'error', type: 'document', error: String(error) }),
          { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
    }

    // Extract text message
    let messageText = webhook.data?.body || '';

    // Clean up bot mentions
    messageText = messageText.replace(/@phoenix\s*ai/gi, '').replace(/@phoenix/gi, '').trim();

    if (!messageText) {
      if (messageType === 'sticker' || messageType === 'reaction') {
        return new Response(
          JSON.stringify({ status: 'ignored', type: messageType }),
          { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }

      await sendMessage(chatId, `🔥 Hey ${senderName}! Try sending me text, an image, a voice note, or a document (PDF, TXT, etc.) and I'll help you out!`, instanceId, token);
      return new Response(
        JSON.stringify({ status: 'handled', type: 'non-text' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Memory commands
    const memoryCmd = detectMemoryCommand(messageText);
    if (memoryCmd.type !== 'none') {
      if (memoryCmd.type === 'save' && memoryCmd.fact) {
        const saved = await saveUserMemory(supabase, 'whatsapp', chatId, memoryCmd.fact);
        const reply = saved
          ? `🧠 Got it, ${senderName}! I'll remember that: "${memoryCmd.fact}" 🔥`
          : `😔 Sorry, I couldn't save that memory. Please try again.`;
        await sendMessage(chatId, reply, instanceId, token);
        await saveMessage(supabase, conversation.id, chatId, 'user', messageText);
        await saveMessage(supabase, conversation.id, chatId, 'assistant', reply);
        return new Response(JSON.stringify({ status: 'success', type: 'memory_save' }),
          { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
      }
      if (memoryCmd.type === 'recall') {
        const memories = await getUserMemories(supabase, 'whatsapp', chatId);
        const reply = memories.length > 0
          ? `🧠 *Here's what I remember about you, ${senderName}:*\n\n${memories.map(m => `• ${m.fact}`).join('\n')}`
          : `🧠 I don't have any saved memories for you yet. Tell me things like "Remember that my name is..." and I'll keep them! 🔥`;
        await sendMessage(chatId, reply, instanceId, token);
        return new Response(JSON.stringify({ status: 'success', type: 'memory_recall' }),
          { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
      }
      if (memoryCmd.type === 'forget') {
        const count = await deleteUserMemories(supabase, 'whatsapp', chatId, memoryCmd.forgetQuery);
        const reply = count > 0
          ? `🧠 Done! I've forgotten ${count} ${count === 1 ? 'memory' : 'memories'}. 🔥`
          : `🧠 I didn't find any matching memories to forget, ${senderName}.`;
        await sendMessage(chatId, reply, instanceId, token);
        return new Response(JSON.stringify({ status: 'success', type: 'memory_forget' }),
          { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
      }
    }

    // Special commands (help, clear, save, language, poll)
    const command = parseCommand(messageText);
    if (command.isCommand) {
      switch (command.command) {
        case 'help':
          await sendMessage(chatId, getHelpMessage(), instanceId, token);
          return new Response(JSON.stringify({ status: 'success', command: 'help' }),
            { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
        case 'clear':
          await clearConversation(supabase, chatId);
          await sendMessage(chatId, `🧹 Done ${senderName}! I've cleared our conversation history. Let's start fresh! 🔥\n\nWhat would you like to talk about?`, instanceId, token);
          return new Response(JSON.stringify({ status: 'success', command: 'clear' }),
            { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
        case 'save':
          await sendMessage(chatId, `💾 Conversation saved ${senderName}! All our chat history is securely stored. 🔥`, instanceId, token);
          return new Response(JSON.stringify({ status: 'success', command: 'save' }),
            { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
        case 'language':
          if (command.language) {
            await updateConversationLanguage(supabase, conversation.id, command.language);
            const langNames: Record<string, string> = {
              en: 'English', fr: 'French', es: 'Spanish', de: 'German',
              pt: 'Portuguese', zh: 'Chinese', ja: 'Japanese', ar: 'Arabic',
              hi: 'Hindi', ru: 'Russian', it: 'Italian', yo: 'Yoruba',
              ha: 'Hausa', ig: 'Igbo', pcm: 'Nigerian Pidgin',
            };
            await sendMessage(chatId, `🗣️ Got it ${senderName}! From now on, I'll respond in *${langNames[command.language] || command.language}*. 🔥`, instanceId, token);
          }
          return new Response(JSON.stringify({ status: 'success', command: 'language' }),
            { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
        case 'poll':
          if (command.pollData) {
            // UltraMsg doesn't have native poll - use text format
            await sendMessage(chatId, formatPoll(command.pollData.question, command.pollData.options), instanceId, token);
          }
          return new Response(JSON.stringify({ status: 'success', command: 'poll' }),
            { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
      }
    }

    // Check for pending documents trigger ("analyze", "compare", "process")
    if (/^(analyze|compare|process|go ahead|do it|yes)$/i.test(messageText.trim())) {
      const pendingDocs = await getPendingDocuments(supabase, chatId);
      if (pendingDocs.length > 0) {
        await clearPendingDocuments(supabase, chatId);

        if (pendingDocs.length === 1) {
          await sendMessage(chatId, `📄 Analyzing *${pendingDocs[0].file_name}*... 🔥`, instanceId, token);
          await saveMessage(supabase, conversation.id, chatId, 'user', `[Sent document: "${pendingDocs[0].file_name}"]`);

          const analysisResponse = await processWithPhoenixAI(
            'Analyze this document and provide a comprehensive summary with key points.',
            senderName, history, conversation.preferred_language,
            `\n\n📄 DOCUMENT CONTENT (${pendingDocs[0].file_name}):\n---\n${pendingDocs[0].extracted_text.slice(0, 25000)}\n---`,
            supabase, chatId
          );
          await saveMessage(supabase, conversation.id, chatId, 'assistant', analysisResponse);
          await sendMessage(chatId, analysisResponse, instanceId, token);
        } else {
          const docNames = pendingDocs.map(d => d.file_name).join(', ');
          await sendMessage(chatId, `📄 Comparing *${pendingDocs.length} documents*: ${docNames}... 🔥`, instanceId, token);
          await saveMessage(supabase, conversation.id, chatId, 'user', `[Comparing ${pendingDocs.length} documents: ${docNames}]`);

          const comparisonResponse = await compareDocuments(
            pendingDocs, '', senderName, history, conversation.preferred_language, supabase, chatId
          );
          await saveMessage(supabase, conversation.id, chatId, 'assistant', comparisonResponse);
          await sendMessage(chatId, comparisonResponse, instanceId, token);
        }

        return new Response(
          JSON.stringify({ status: 'success', type: 'document_trigger', docCount: pendingDocs.length }),
          { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
    }

    // Image generation
    const imageRequest = detectImageGenerationRequest(messageText);
    if (imageRequest.shouldGenerate) {
      const result = await generateImage(imageRequest.prompt, imageRequest.quality, lovableApiKey);
      if (result.success && result.imageBase64) {
        await saveMessage(supabase, conversation.id, chatId, 'user', messageText);
        const imageSent = await sendImageMessage(
          chatId,
          result.imageBase64,
          `🎨 *${imageRequest.prompt.slice(0, 100)}*`,
          instanceId,
          token
        );
        if (imageSent) {
          await saveMessage(supabase, conversation.id, chatId, 'assistant', `[Generated image: ${imageRequest.prompt}]`);
          return new Response(JSON.stringify({ status: 'success', type: 'image_generation' }),
            { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
        }
      }
      await saveMessage(supabase, conversation.id, chatId, 'user', messageText);
      await sendMessage(chatId, `😔 Sorry ${senderName}, I couldn't generate that image. ${result.error || 'Please try again!'} 🔥`, instanceId, token);
      return new Response(JSON.stringify({ status: 'handled', type: 'image_generation' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    }

    // Add quoted message context (swipe-reply)
    let contextualMessage = messageText;
    if (webhook.data?.quotedMsg?.body) {
      contextualMessage = `[Replying to: "${webhook.data.quotedMsg.body.slice(0, 300)}"]\n\n${messageText}`;
    }

    // Save user message
    await saveMessage(supabase, conversation.id, chatId, 'user', contextualMessage);

    // Process with AI
    let aiResponse: string;
    try {
      aiResponse = await processWithPhoenixAI(
        contextualMessage,
        senderName,
        history,
        conversation.preferred_language,
        undefined,
        supabase,
        chatId
      );
    } catch (error) {
      console.error('AI processing failed:', error);
      aiResponse = `Hey ${senderName}! 🔥 I had a brief hiccup processing that. Could you rephrase or try again?`;
    }

    await saveMessage(supabase, conversation.id, chatId, 'assistant', aiResponse);
    await sendMessage(chatId, aiResponse, instanceId, token);

    return new Response(
      JSON.stringify({ status: 'success', historyLength: history.length + 2 }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error: unknown) {
    console.error('UltraMsg webhook error:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
